nome=input('qual o seu nome?')
print('olá', nome, 'é um prazer te conhecer!')
print('qual dia você nasceu?')
idadeD=input('dia:')
idadeM=input('mes:')
idadeA=input('ano:')
print('ah então você nasceu no dia', idadeD, '/', idadeM, '/', idadeA, 'certo?')
